sonar.projectKey=lucasac00_wagtail
sonar.organization=es2-grupo03-ufscar

sonar.python.version=3.10, 3.11, 3.12, 3.13, 3.14
sonar.sources=wagtail
sonar.exclusions=wagtail/**/migrations/**,wagtail/**/tests/**,wagtail/test/**,wagtail/**/static_src/**

# Tell SonarCloud exactly where the Python coverage file is
sonar.python.coverage.reportPaths=coverage.xml

# Clear out JavaScript coverage tracking completely
sonar.javascript.lcov.reportPaths=
