name: CI - Grupo 03

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -e ".[testing]"
      - run: python runtests.py
      - run: coverage run --source wagtail runtests.py
      - run: coverage report -m
      - run: coverage html
      - run: coverage xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@e44258b109568baa0df60ed515909fc6c72cba92  # v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_html_report/

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run test:unit
